# Generated by Django 4.2.1 on 2023-06-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('photo', models.TextField()),
            ],
        ),
    ]
