# Generated by Django 4.2.1 on 2023-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='fauvorite',
            field=models.BooleanField(default=False),
        ),
    ]
